### ISSUE TITLE
Driver not found

### ISSUE THREAD

**Issue by smoslinux** [nicolargo/pyadl#4]
Hi, I saw the new version of this software and I tried to run, but I have an issue with ADL. This is Linux environment and the amd-pro drivers are installed 17.40

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    from pyadl import *
  File "/opt/pyadl/pyadl/__init__.py", line 11, in <module>
    from .pyadl import *
  File "/opt/pyadl/pyadl/pyadl.py", line 28, in <module>
    raise ADLError("Driver not found!")
pyadl.pyadl.ADLError: Driver not found!
```

**Comment by hunasdf** [comment]
Hi, I cannot test it on linux, I have installed only windows (or mac :D). If you can wait a few days, I will install one and try to fix this problem. 
On the other hand, this part of code is based on adl3 lib. I did not make any modification to load the driver. (adl_api.py from line 38 to 48). And based on the documentation, the loading procedure looks fine :)

**Comment by smoslinux** [comment]
For some reason, the system still cannot find ADL lib. Not sure why.

**Comment by smoslinux** [comment]
Yes, please do it. 👍

**Comment by hunasdf** [comment]
I do not forget it! Just my machine failed :( The distributor is replacing the motherboard... Sorry for the delay!

**Comment by smoslinux** [comment]
Thanks! I'm waiting for your response :)

**Comment by hunasdf** [comment]
Finally, I could install an Ubuntu 16.04 to my machine and I got the same issue like you. But the bad news: AMD ADL lib is not supported by the amdgpu-pro driver (reference: https://bugs.freedesktop.org/show_bug.cgi?id=96786) :( But I did not find any official news or something about that. Based on the documentation and the official webpage of ADL, linux is supported. Just not working for anyone :D 
As a result, we have to find an other alternative on linux, like hwmon and sysfs as it wrote in the comment or maybe opencl.
